server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root@123
    driver-class-name: com.mysql.jdbc.Driver

#JPA Setting
#  jpa.hibernate.ddl_auto: create